---
# tasks to uninstall IPA client

- name: Uninstall - Uninstall IPA client
  ipaclient:
    state: absent

#- name: Remove IPA client package
#  package:
#    name: "{{ item }}"
#    state: absent
#  with_items: "{{ ipaclient_packages }}"
